version: '3'

services:
  demo:
    image: nginxdemos/hello
    container_name: demo_app
    restart: "always"
    expose:
      - 80
    environment:
      VIRTUAL_HOST: <host>
      LETSENCRYPT_HOST: <host>
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
